### ISSUE TITLE
Missed Hikari-Swift/swiftpm/Sources/Build folder

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-Swift#1]
Glad to see the project is under the active development!
I faced with below build issue:
```
CMake Error at Sources/CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "Build" which is not an existing directory.
```
Could you, please, double check the folder **Hikari-Swift/swiftpm/Sources/Build** is not missed.
The Hikari-Swift/swiftpm/Sources/CMakeLists.txt adds such subdirectories
```
add_subdirectory(Basics)
add_subdirectory(Build)
add_subdirectory(Commands)
add_subdirectory(LLBuildManifest)
...
```
but the **Hikari-Swift/swiftpm/Sources/Build** folder is missed in this repo.

**Comment by NeHyci** [comment]
should be fixed in [https://github.com/NeHyci/Hikari-Swift/commit/0bef8f33772a6d4566427824c46b6a9aac28501d](https://github.com/NeHyci/Hikari-Swift/commit/0bef8f33772a6d4566427824c46b6a9aac28501d), can you try again?
